### ISSUE TITLE
[QUESTION]: Is it acceptable to increase the precision of the temporal values?

### ISSUE THREAD

**Issue by jyelloz** [mrsarm/rust-sum-queue#2]
Hi, I am working on a tool that has a feature which measures recent I/O throughput for a copy operation so this library looked like a pretty good fit. It mostly works okay but an issue I ran into, though, is that for a short time window (2-5 seconds with sum values ranging from 10..10,000), the summations produced by this library have been off by a bit, typically about 10%. I looked into the code a little bit and found that if I switched the QueueElement's `time` to `std::time::Instant` and SumQueue's `max_age` to `std::time::Duration`, the summations computed by it will match up properly with the data I am measuring externally.

Anyway, I am just wondering if you'd consider a change to increase the time measurement/math precision by relying on the standard library's time values in order to make it more accurate? It should be possible to maintain API compatibility since only the internal representations would change.

**Comment by mrsarm** [comment]
Hi @jyelloz , what you said makes sense, I didn't test the library in such a constraint times. Could you provide a PR with the changes needed? I would be glad to test it soon, and make a new release with the changes.

**Comment by mrsarm** [comment]
Released in version [1.0.0](https://github.com/mrsarm/rust-sum-queue/releases/tag/1.0.0).
